name: Chromatic test

on:
    pull_request:

    push:
        branches:
            - main

jobs:
    frontend-unit-test:
        name: Node ${{ matrix.node }} - Unit

        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: packages/ui

        strategy:
            matrix:
                node: ['18']

        steps:
            - name: Checkout the repository to Github workspace
              uses: actions/checkout@v3
              with:
                fetch-depth: 0

            - name: Setup the Node environment
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}

            - uses: pnpm/action-setup@v2.0.1
              name: Install pnpm
              id: pnpm-install
              with:
                version: 7
                run_install: false

            - name: Get pnpm store directory
              id: pnpm-cache
              run: |
                echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

            - uses: actions/cache@v3
              name: Setup pnpm cache
              with:
                path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
                key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                restore-keys: |
                  ${{ runner.os }}-pnpm-store-

            - name: Install dependencies
              run: pnpm --filter ui install

            - name: Publish to Chromatic
              uses: chromaui/action@v1
              with:
                projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
                storybookConfigDir: .storybook
                buildScriptName: build
